
name: CI-CD

on:
  pull_request:
  push:
    branches: [ "main" ]
  merge_group:
    types: checks_requested
    

  workflow_dispatch:
  

jobs:

  #1. Detecta Mudança em Determinados Diretórios
  detect-changes:
    runs-on: ubuntu-latest
    
    outputs:
      java: ${{ steps.filter.outputs.java }}
      python: ${{ steps.filter.outputs.python }}
      front: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            java:
              - 'backend/sistema-java/app/**'
            python:
              - 'backend/ai-python/**'
            frontend:
              - 'frontend/**'



  #2. CI JAVA COM BUILD E TEST
  java:
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.java == 'true'

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: eleicoes_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
          
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build + Test Java
        working-directory: 'backend/sistema-java/app/'
        run: mvn clean install
        env:
          DB_USER_POSTGRES: postgres
          DB_URL: jdbc:postgresql://localhost:5432/eleicoes_db
          DB_PASSWORD_POSTGRES: postgres


  #3. CI PYTHON COM BUILD E TEST
  python:
    environment: development
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.python == 'true'
    env:
      APP_ENV:
      GOOGLE_API_KEY: ${{secrets.IA_SERVICE_GOOGLE_API_KEY_1}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_REGION}}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências
        working-directory: 'backend/ai-python/'
        run: pip install -r requirements.txt

      - name: Rodar testes
        working-directory: 'backend/ai-python/'
        run: pytest



  #4. PREPARAR VERSÃO DA IMAGEM DOCKER
  prepare:
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'

    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

          

  #5. BUILD IMAGEM DE JAVA E PUBLICAR NO DOCKER HUB
  build-java-image:
    runs-on: ubuntu-latest
    needs: [prepare, detect-changes, java, terraform]
    if: needs.detect-changes.outputs.java == 'true' && github.event_name == 'merge_group'

    steps:
    - uses: actions/checkout@v4
        
    - name: Build da Imagem Java
      run: |
        docker build \
            -t ${{ secrets.DOCKER_HUB_USER }}/system-eleic:${{ needs.prepare.outputs.tag }} \
            -t ${{ secrets.DOCKER_HUB_USER }}/system-eleic:latest \
            ./backend/sistema-java/app
            
    - name: Login Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push Docker Hub Image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/system-eleic:${{ needs.prepare.outputs.tag }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/system-eleic:latest


  #6. BUILD IMAGEM DE PYTHON E PUBLICAR NO DOCKER HUB
  build-python-image:
    runs-on: ubuntu-latest
    needs: [prepare, detect-changes, python, terraform]
    if: needs.detect-changes.outputs.python == 'true' && github.event_name == 'merge_group'

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{secrets.DOCKER_HUB_USER_PYTHON}}
        password: ${{secrets.DOCKER_HUB_TOKEN_PYTHON}}
    
    - name: Build da Imagem Python
      run: |
        docker build \
              -t ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:${{ needs.prepare.outputs.tag }} \
              -t ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:latest \
              "./backend/ai-python"
            
    - name: Push Imagem Python
      run: |
          docker push ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:${{ needs.prepare.outputs.tag }}
          docker push ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:latest


  #7. BUILD DA IMAGEM DO FRONTEND
  build-front-image:
    runs-on: ubuntu-latest
    needs: [detect-changes, prepare, terraform]
    if: github.event_name == 'merge_group'
  
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
  
      - name: Terraform Init for outputs
        working-directory: system-deploy/terraform/envs/prod
        run: terraform init
  
      - name: Get ALB DNS from Terraform state
        working-directory: system-deploy/terraform/envs/prod
        run: |
          ALB_DNS_NAME="$(terraform output -raw alb_dns_name)"
  
          echo "ALB DNS recebido do state: '$ALB_DNS_NAME'"
  
          test -n "$ALB_DNS_NAME" || (echo "ALB DNS vazio" && exit 1)
  
          echo "ALB_DNS_NAME=$ALB_DNS_NAME" >> "$GITHUB_ENV"
  
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USER_FRONT }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_FRONT }}
  
      - name: Build da Imagem Front
        run: |
          BACKEND_URL="http://${ALB_DNS_NAME}"
  
          echo "Building frontend with NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL"
  
          test "$BACKEND_URL" != "http://" || (echo "BACKEND_URL inválido" && exit 1)
  
          docker build \
            --build-arg NEXT_PUBLIC_BACKEND_URL="$BACKEND_URL" \
            -t ${{ secrets.DOCKER_HUB_USER_FRONT }}/frontend-tcc:${{ needs.prepare.outputs.tag }} \
            -t ${{ secrets.DOCKER_HUB_USER_FRONT }}/frontend-tcc:latest \
            "./frontend"
  
      - name: Push Imagem Front
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER_FRONT }}/frontend-tcc:${{ needs.prepare.outputs.tag }}
          docker push ${{ secrets.DOCKER_HUB_USER_FRONT }}/frontend-tcc:latest


  #8. TERRAFORM EXECUTION
  terraform:
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'

    outputs:
      instance_id: ${{ steps.tf_outputs.outputs.instance_id }}
      app_secret_id: ${{ steps.tf_outputs.outputs.app_secret_id }}
      alb_dns_name: ${{ steps.tf_outputs.outputs.alb_dns_name }}

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
      
      TF_VAR_aws_region: ${{secrets.AWS_REGION}}
      TF_VAR_app_aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
      TF_VAR_app_aws_secret_key: ${{secrets.AWS_SECRET_KEY}}

      TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
      TF_VAR_db_name: ${{secrets.DB_NAME}}
      TF_VAR_db_username: ${{secrets.DB_USERNAME}}
      TF_VAR_db_password: ${{secrets.DB_PASSWORD}}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: system-deploy/terraform/envs/prod
      run: terraform init

    - name: Terraform Validate
      working-directory: system-deploy/terraform/envs/prod
      run: terraform validate

    - name: Terraform Apply
      working-directory: system-deploy/terraform/envs/prod
      run: terraform apply -auto-approve

    - name: Get EC2 instance ID
      id: tf_outputs
      working-directory: system-deploy/terraform/envs/prod
      run: |
        echo "instance_id=$(terraform output -raw ec2_instance_id)" >> "$GITHUB_OUTPUT"
        echo "app_secret_id=$(terraform output -raw app_secret_id)" >> "$GITHUB_OUTPUT"
        echo "alb_dns_name=$(terraform output -raw alb_dns_name)" >> "$GITHUB_OUTPUT"




  #9. Deploy 
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs:
      - terraform
      - build-front-image
      - build-java-image

  
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
  
      INSTANCE_ID: ${{ needs.terraform.outputs.instance_id }}
      APP_SECRET_ID: system-eleic-2/app
  
    steps:
      - name: Validate deploy inputs
        run: |
          test -n "$INSTANCE_ID" || (echo "INSTANCE_ID vazio" && exit 1)
          test -n "$APP_SECRET_ID" || (echo "APP_SECRET_ID vazio" && exit 1)
          test -n "$AWS_REGION" || (echo "AWS_REGION vazio" && exit 1)
  
      - name: Deploy through SSM
        run: |
          echo "Deploying to instance: $INSTANCE_ID"
          echo "Using secret: $APP_SECRET_ID"
  
          jq -n \
            --arg secret_id "$APP_SECRET_ID" \
            --arg region "$AWS_REGION" \
            '{
              commands: [
                "set -eu",
                "APP_DIR=/opt/system-eleic",
                "cd $APP_DIR",
  
                ("SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id " + $secret_id + " --region " + $region + " --query SecretString --output text)"),
  
                "export DB_URL=$(echo \"$SECRET_JSON\" | jq -r \".DB_URL\")",
                "export DB_USER_POSTGRES=$(echo \"$SECRET_JSON\" | jq -r \".DB_USER_POSTGRES\")",
                "export DB_PASSWORD_POSTGRES=$(echo \"$SECRET_JSON\" | jq -r \".DB_PASSWORD_POSTGRES\")",
                "export AWS_REGION=$(echo \"$SECRET_JSON\" | jq -r \".AWS_REGION\")",
                "export AWS_ACCESS_KEY=$(echo \"$SECRET_JSON\" | jq -r \".AWS_ACCESS_KEY\")",
                "export AWS_SECRET_KEY=$(echo \"$SECRET_JSON\" | jq -r \".AWS_SECRET_KEY\")",
  
                "sudo -E docker compose pull",
                "sudo -E docker compose up -d"
              ]
            }' > ssm-params.json
  
          cat ssm-params.json
  
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy system-eleic application" \
            --parameters file://ssm-params.json \
            --query "Command.CommandId" \
            --output text)
  
          echo "Command ID: $COMMAND_ID"
  
          set +e

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID"
          
          WAIT_EXIT_CODE=$?
          
          echo "=== SSM COMMAND RESULT ==="
          
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --query "{Status:Status,Stdout:StandardOutputContent,Stderr:StandardErrorContent}" \
            --output json
          
          exit $WAIT_EXIT_CODE
      
  
